# Generated by Django 4.1 on 2025-06-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = []
